name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

env:
  ACR_NAME: terraformlearning
  RESOURCE_GROUP: terraform-learning-rg
  LOCATION: West Europe
  ACR_LOGIN_SERVER: terraformlearning.azurecr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 🔁 Login to ACR
        run: |
          az acr login --name $ACR_NAME

      - name: 🔐 Inject VITE_API_URL from GitHub Secret
        run: |
          echo "VITE_API_URL=${{ secrets.FRONTEND_API_URL }}" > ./frontend/.env.production

      - name: 🐳 Build and Push Frontend
        run: |
          docker build -t $ACR_LOGIN_SERVER/frontend:latest ./frontend
          docker push $ACR_LOGIN_SERVER/frontend:latest

      - name: 🐳 Build and Push Backend
        run: |
          docker build -t $ACR_LOGIN_SERVER/backend:latest ./backend
          docker push $ACR_LOGIN_SERVER/backend:latest

      - name: ⚙️ Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: 🧱 Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: 🚀 Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: 🔄 Restart Azure App Services (Force Re-pull)
        run: |
          az webapp restart --name vite-container-frontend --resource-group $RESOURCE_GROUP
          az webapp restart --name express-container-backend --resource-group $RESOURCE_GROUP
